version: '3'

services:
  auth-service:
    build: .
    ports:
      - "6000:6000"
    links:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb+srv://iamanuragsaini0:yFSElJkFyFhp5ASo@cluster0.fkqgjqi.mongodb.net
      - REDIS_URI=redis://127.0.0.1:6379

  mongo:
    image: mongo
    ports:
      - "27018:27017"

  redis:
    image: redis
    ports:
      - "6380:6379"
